export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_SERVICES = "GET_SERVICES";
export const CHANGE_COMPONENT_STATE = "CHANGE_COMPONENT_STATE";
export const GET_SERVICE = "GET_SERVICE";
